name: flutter_youtube_bloc_provider
description: DESIGN PATTERNS (BLOC) AND PROVIDER STATE MANAGEMENT
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_youtube: ^2.0.0
  http: ^0.12.0+4
  shared_preferences: ^0.5.6
  provider: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/